# Generated by Django 4.2.2 on 2023-06-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=5000)),
                ('img', models.ImageField(upload_to='', verbose_name='/company_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_number', models.CharField(max_length=30)),
                ('emile', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('discription', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('emile', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('discription', models.CharField(max_length=5000)),
                ('youtube_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='', verbose_name='/news_imgs')),
                ('appeal', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emile', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('check_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
